/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health */
		get: operations['health_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/ping': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Ping */
		get: operations['ping_health_ping_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agents/wing/invoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Invoke Wing Agent */
		post: operations['invoke_wing_agent_agents_wing_invoke_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/** WingAgentError */
		WingAgentError: {
			/**
			 * Code
			 * @enum {string}
			 */
			code: 'agent_error' | 'data_unavailable';
			/** Message */
			message: string;
		};
		/** WingAgentRequest */
		WingAgentRequest: {
			/** Message */
			message: string;
			/** Thread Id */
			thread_id?: string | null;
			/** Additional Prompt */
			additional_prompt?: string | null;
			/**
			 * Agent Profile
			 * @default imports
			 * @enum {string}
			 */
			agent_profile: 'insights' | 'imports' | 'planning';
		};
		/**
		 * WingAgentResponse
		 * @description The public outcome of one Wing agent turn.
		 */
		WingAgentResponse: {
			/**
			 * Thread Id
			 * Format: uuid
			 */
			thread_id: string;
			/** Turn Id */
			turn_id: string;
			/** Answer */
			answer: string;
			/** Results */
			results?: components['schemas']['WingAgentResult'][];
			/** Applied Filters */
			applied_filters?: Record<string, never> | null;
			error?: components['schemas']['WingAgentError'] | null;
		};
		/**
		 * WingAgentResult
		 * @description A UI-safe, structured result produced during the current turn.
		 */
		WingAgentResult: {
			/** Id */
			id: string;
			/**
			 * Type
			 * @enum {string}
			 */
			type:
				| 'cash_flow_history'
				| 'spending_by_category'
				| 'transaction_summary'
				| 'transaction_list'
				| 'transactions_by_category';
			/** Data */
			data: Record<string, never> | Record<string, never>[];
			/** Ui */
			ui?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	health_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	ping_health_ping_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	invoke_wing_agent_agents_wing_invoke_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WingAgentRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WingAgentResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
